//    KriolOS POS
//    Copyright (c) 2019-2026 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
package com.openbravo.beans;

import com.openbravo.data.gui.modal.PosUIModal;
import java.awt.Component;
import javax.swing.Icon;
import javax.swing.JPanel;

/**
 * Panel for entering diner/guest counts, presentable modally via {@link PosUIModal} or embedded directly into views.
 *
 * @author KriolOS
 */
public class DinerNumberPanel extends JPanel {

    private static final long serialVersionUID = 1L;
    private static LocaleResources m_resources;

    private PosUIModal modalContext;
    private Double m_value;
    private boolean accepted = false;

    /**
     * Creates new form DinerNumberPanel
     */
    public DinerNumberPanel() {
        init();
    }

    private void init() {
        if (m_resources == null) {
            m_resources = new LocaleResources();
            m_resources.addBundleName("beans_messages");
        }

        initComponents();

        m_jnumber.addEditorKeys(m_jKeys);
        m_jnumber.reset();
        m_jnumber.setDoubleValue(1.0);
        m_jnumber.activate();

        m_jPanelTitle.setBorder(RoundedBorder.createGradientBorder());
        m_value = null;
        initDomainAdapters();
    }

    private void initDomainAdapters() {
        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        setName("kriolos:dining:guest-count-panel");
        m_jKeys.setName("kriolos:dining:guest-count-keypad");
        m_jnumber.setName("kriolos:dining:guest-count-field");
        jcmdOK.setName("kriolos:dining:guest-count-btn-ok");
        m_lblMessage.setName("kriolos:dining:guest-count-lbl-message");
    }

    /**
     * Attaches the host {@link PosUIModal} context.
     *
     * @param modalContext the controlling modal context
     */
    public void setModalContext(PosUIModal modalContext) {
        this.modalContext = modalContext;
    }

    /**
     * Sets the header message and icon.
     *
     * @param message the message text
     * @param icon the message icon
     */
    public void setMessage(String message, Icon icon) {
        m_lblMessage.setText(message);
        m_lblMessage.setIcon(icon);
    }

    /**
     * Retrieves the entered guest count number.
     *
     * @return the entered Double value
     */
    public Double getValue() {
        return m_value;
    }

    /**
     * Returns whether the panel entry was confirmed by the user.
     *
     * @return true if accepted, false if canceled
     */
    public boolean isAccepted() {
        return accepted;
    }

    private void handleAccept() {
        this.accepted = true;
        this.m_value = m_jnumber.getValue();
        if (modalContext != null) {
            modalContext.setResult(m_value);
            modalContext.close();
        }
    }

    /**
     * Factory presentation method using {@link PosUIModal}.
     *
     * @param parent the parent component or window
     * @param title the modal window/overlay title
     * @param message header message
     * @param icon header icon
     * @return the entered guest count, or {@code null} if dismissed
     */
    public static Double show(Component parent, String title, String message, Icon icon) {
        DinerNumberPanel panel = new DinerNumberPanel();
        panel.setMessage(message, icon);

        PosUIModal modal = PosUIModal.create(parent, panel)
                .setTitle(title)
                .setModal(true)
                .setResizable(false);

        panel.setModalContext(modal);
        modal.show();

        return panel.isAccepted() ? panel.getValue() : null;
    }

    public static Double show(Component parent, String title, String message) {
        return show(parent, title, message, null);
    }

    public static Double show(Component parent, String title) {
        return show(parent, title, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelGrid = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        m_jKeys = new com.openbravo.editor.JEditorKeys();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        m_jnumber = new com.openbravo.editor.JEditorDoublePositive();
        jcmdOK = new javax.swing.JButton();
        m_jPanelTitle = new javax.swing.JPanel();
        m_lblMessage = new javax.swing.JLabel();

        // Root size intentionally omitted: PosUIModal calls pack() which computes
        // natural size from children. Fixed root sizes are fragile against padding changes.
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        m_jKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jKeysActionPerformed(evt);
            }
        });
        jPanel3.add(m_jKeys);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        m_jnumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_jnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_jnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jcmdOK.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcmdOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/ok.png"))); // NOI18N
        jcmdOK.setMargin(new java.awt.Insets(8, 16, 8, 16));
        jcmdOK.setPreferredSize(new java.awt.Dimension(80, 45));
        jcmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdOKActionPerformed(evt);
            }
        });
        jPanel4.add(jcmdOK, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanelGrid.add(jPanel3);

        jPanel2.add(jPanelGrid, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        m_jPanelTitle.setLayout(new java.awt.BorderLayout());

        m_lblMessage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        m_jPanelTitle.add(m_lblMessage, java.awt.BorderLayout.CENTER);

        add(m_jPanelTitle, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdOKActionPerformed
        handleAccept();
    }//GEN-LAST:event_jcmdOKActionPerformed

    private void m_jKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jKeysActionPerformed
    }//GEN-LAST:event_m_jKeysActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGrid;
    private javax.swing.JButton jcmdOK;
    private com.openbravo.editor.JEditorKeys m_jKeys;
    private javax.swing.JPanel m_jPanelTitle;
    private com.openbravo.editor.JEditorDoublePositive m_jnumber;
    private javax.swing.JLabel m_lblMessage;
    // End of variables declaration//GEN-END:variables
}
