<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.kriolos.opos</groupId>
        <artifactId>kriolos-opos-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>kriolos-krpos-jpackage</artifactId>
    <packaging>pom</packaging>
    <name>Kriolos.POS.JPackage</name>
    
    <properties>
        <appModule>io.github.kriolos.opos</appModule>
        <appMainClass>com.openbravo.pos.forms.StartPOS</appMainClass>
        <appJar>kriolos-opos-app-1.0.0-SNAPSHOT.jar</appJar>
    </properties>
 
    <dependencies>
        <dependency>
            <groupId>io.github.kriolos.opos</groupId>
            <artifactId>kriolos-opos-app</artifactId>
        </dependency>
    </dependencies>
    
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>copy-dependencies</id>
                            <phase>package</phase>
                            <goals>
                                <goal>copy-dependencies</goal>
                            </goals>
                            <configuration>
                                <includeScope>runtime</includeScope>
                                <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.panteleyev</groupId>
                    <artifactId>jpackage-maven-plugin</artifactId>
                    <executions>
                        <!-- Execution 1: Standalone Application Directory (App Image) without license flag -->
                        <execution>
                            <id>create-app-image</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jpackage</goal>
                            </goals>
                            <configuration>
                                <type>APP_IMAGE</type>
                                <destination>${project.build.directory}/dist/image</destination>
                            </configuration>
                        </execution>

                        <!-- Execution 2: Native Installer (DEB, MSI, or DMG) with license flag -->
                        <execution>
                            <id>create-installer</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jpackage</goal>
                            </goals>
                            <configuration>
                                <destination>${project.build.directory}/dist/installer</destination>
                                <type>${installer.type}</type>
                                <icon>${app.icon}</icon>
                                <aboutUrl>https://github.com/kriolos-obiz/kriolos-pos</aboutUrl>
                                <licenseFile>${project.basedir}/../LICENSE</licenseFile>

                                <!-- MACOS OPTION -->
                                <macPackageIdentifier>io.github.kriolos-obiz.opos</macPackageIdentifier>

                                <!-- WINDOWS OPTION -->
                                <winMenu>true</winMenu>
                                <winMenuGroup>KriolOS/OPOS</winMenuGroup>
                                <winDirChooser>true</winDirChooser>

                                <!-- LINUX OPTION -->
                                <linuxShortcut>true</linuxShortcut>
                                <linuxPackageName>kriolos-pos</linuxPackageName>
                                <linuxAppCategory>Office</linuxAppCategory>
                                <linuxMenuGroup>Office</linuxMenuGroup>
                                <linuxDebMaintainer>Paulo Borges (aka poolborges)</linuxDebMaintainer>
                            </configuration>
                        </execution>
                    </executions>
                    <configuration>
                        <name>kriolosPOS</name>
                        <appVersion>1.0.0</appVersion>
                        <copyright>Paulo Borges</copyright>
                        <description>KriolOS Point of Sales</description>
                        <vendor>KriolOS</vendor>
                        <input>${project.build.directory}/lib</input>
                        <mainClass>${appMainClass}</mainClass>
                        <mainJar>${appJar}</mainJar>
                        <destination>${project.build.directory}/dist</destination>

                        <launchers>
                            <launcher>
                                <name>kriolosPOS-Config</name>
                                <file>${project.basedir}/jpackage/launcher-pos-config.properties</file>
                            </launcher>
                        </launchers>

                        <javaOptions>
                            <option>-Dfile.encoding=UTF-8</option>
                            <option>--add-opens=java.desktop/java.beans=ALL-UNNAMED</option>
                            <option>--add-opens=java.base/java.io=ALL-UNNAMED</option> 
                            <option>--add-opens=java.base/java.lang.ref=ALL-UNNAMED</option>
                            <option>--add-opens=java.base/java.lang=ALL-UNNAMED</option>
                            <option>--add-opens=java.base/java.util=ALL-UNNAMED</option> 
                        </javaOptions>

                        <jLinkOptions>
                            <jLinkOption>--strip-native-commands</jLinkOption>
                            <jLinkOption>--strip-debug</jLinkOption>
                            <jLinkOption>--no-man-pages</jLinkOption>
                            <jLinkOption>--no-header-files</jLinkOption>
                            <jLinkOption>--compress=2</jLinkOption>
                        </jLinkOptions>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <!-- Profile per OS: provides OS-specific properties & configuration without triggering execution -->
        <profile>
            <id>jpackage-windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <installer.type>MSI</installer.type>
                <app.icon>${project.basedir}/icons/app_icon.ico</app.icon>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.panteleyev</groupId>
                            <artifactId>jpackage-maven-plugin</artifactId>
                            <configuration>
                                <javaOptions>
                                    <option>-Dfile.encoding=UTF-8</option>
                                    <option>-Dawt.useSystemAAFontSettings=on</option>
                                    <option>-Dswing.aatext=true</option>
                                    <option>-Djava.desktop.appName=kriolosPOS</option>
                                    <option>--add-opens=java.desktop/java.beans=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.io=ALL-UNNAMED</option> 
                                    <option>--add-opens=java.base/java.lang.ref=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.lang=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.util=ALL-UNNAMED</option> 
                                </javaOptions>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>

        <profile>
            <id>jpackage-macos</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <installer.type>DMG</installer.type>
                <app.icon>${project.basedir}/icons/app_icon.icns</app.icon>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.panteleyev</groupId>
                            <artifactId>jpackage-maven-plugin</artifactId>
                            <configuration>
                                <javaOptions>
                                    <option>-Dapple.laf.useScreenMenuBar=true</option>
                                    <option>-Dawt.useSystemAAFontSettings=gasp</option>
                                    <option>-Dswing.aatext=true</option>
                                    <option>-Djava.desktop.appName=kriolosPOS</option>
                                    <option>--add-opens=java.desktop/java.beans=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.io=ALL-UNNAMED</option> 
                                    <option>--add-opens=java.base/java.lang.ref=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.lang=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.util=ALL-UNNAMED</option> 
                                </javaOptions>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>

        <profile>
            <id>jpackage-linux</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <properties>
                <installer.type>DEB</installer.type>
                <app.icon>${project.basedir}/icons/app_icon.png</app.icon>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.panteleyev</groupId>
                            <artifactId>jpackage-maven-plugin</artifactId>
                            <configuration>
                                <javaOptions>
                                    <option>-Dfile.encoding=UTF-8</option>
                                    <option>-Dawt.useSystemAAFontSettings=on</option>
                                    <option>-Dswing.aatext=true</option>
                                    <option>-Djava.desktop.appName=kriolosPOS</option>
                                    <option>--add-opens=java.desktop/java.beans=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.io=ALL-UNNAMED</option> 
                                    <option>--add-opens=java.base/java.lang.ref=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.lang=ALL-UNNAMED</option>
                                    <option>--add-opens=java.base/java.util=ALL-UNNAMED</option> 
                                </javaOptions>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>

        <!-- Profile 'release': Activates copy-dependencies & jpackage packaging -->
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Alias profile 'jpackage' to also activate packaging -->
        <profile>
            <id>jpackage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Profile 'rpm': Additional execution for generating RPM installers on Linux -->
        <profile>
            <id>rpm</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>create-installer-rpm</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <destination>${project.build.directory}/dist/installer</destination>
                                    <type>RPM</type>
                                    <icon>${app.icon}</icon>
                                    <aboutUrl>https://github.com/kriolos-obiz/kriolos-pos</aboutUrl>
                                    <licenseFile>${project.basedir}/../LICENSE</licenseFile>
                                    <linuxShortcut>true</linuxShortcut>
                                    <linuxPackageName>kriolos-pos</linuxPackageName>
                                    <linuxAppCategory>Office</linuxAppCategory>
                                    <linuxMenuGroup>Office</linuxMenuGroup>
                                    <linuxRpmLicenseType>GPLv3</linuxRpmLicenseType>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>