//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.sales;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.catalog.CatalogSelector;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.ResourceService;
import com.openbravo.pos.ticket.TicketLineInfo;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author JG uniCenta
 */
public class JTicketCatalogLines extends javax.swing.JPanel {
    
    private JRefundLines refoundLines;
    private CatalogSelector catalogExplorer;

    public JTicketCatalogLines(
            AppView app, 
            JPanelTicketEdits jTicketEdit, 
            boolean pricevisible, 
            boolean taxesincluded, 
            int width, 
            int height) {
        
        ResourceService resourceService = app.getBean(ResourceService.class);
        
        initComponents();
        
        refoundLines = new JRefundLines(resourceService, jTicketEdit);        
        add(refoundLines, "reflines");
        
        catalogExplorer = (CatalogSelector) com.openbravo.pos.ui.api.catalog.CatalogManager.createDefaultCatalog(app);
        catalogExplorer.getComponent().setPreferredSize(new Dimension(0, 245));      
        add(catalogExplorer.getComponent(), "catalog");
    }

    public void showCatalog() {
        showView("catalog");
    }

    public void loadCatalog() throws BasicException {
        catalogExplorer.loadCatalog();
    }

    public void addActionListener(ActionListener l) {
        catalogExplorer.addActionListener(l);
    }

    public void removeActionListener(ActionListener l) {
        catalogExplorer.addActionListener(l);
    }

    public void showRefundLines(List<TicketLineInfo> aRefundLines) {
        // anado las lineas de refund
        refoundLines.setLines(aRefundLines);
        showView("reflines");
    }   
    
    private void showView(String sView) {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, sView);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(getFont());
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
