# ====================================================================
# CONFIGURA\u00c7\u00c3O CORE DO HOTSWAP
# ====================================================================
autoHotswap=true
LOGGER=info

# ====================================================================
# COMPILA\u00c7\u00c3O MULTI-MODULE (VIGIAR PROJETO INTEIRO)
# ====================================================================
# Subimos um n\u00edvel (../) a partir do kriolos-opos-app para monitorizar as classes de cada m\u00f3dulo irm\u00e3o
watch.resources=\
  target/classes,\
  ../kriolos-opos-assets-image/target/classes
  ../kriolos-opos-assets-reports/target/classes
  ../kriolos-opos-base/target/classes,\
  ../kriolos-opos-domain/target/classes,\
  ../kriolos-opos-hardware/target/classes,\
  ../kriolos-opos-i18n/target/classes,\
  ../kriolos-opos-i18n_pt/target/classes,\
  ../kriolos-opos-l10n-pt-cv/target/classes,\
  ../kriolos-opos-lib-report/target/classes,\
  ../kriolos-opos-spi/target/classes,\
  ../kriolos-opos-ui-api/target/classes,\
  ../kriolos-opos-ui-flatlaf/target/classes,\
  ../kriolos-opos-ui-native/target/classes

# ====================================================================
# RECARREGAMENTO DE RECURSOS E TRADU\u00c7\u00d5ES
# ====================================================================
# Garante que os ficheiros de tradu\u00e7\u00e3o (inclusive o teu SPI de Cabo Verde pt-CV) atualizam a quente
plugin.resourceBundle.disabled=false
plugin.hotswap.resources=true

# ====================================================================
# DESATIVAR PLUGINS DESNECESS\u00c1RIOS (PERFORMANCE)
# ====================================================================
plugin.packages.disabled=spring,hibernate,jetty,tomcat,wildfly,glassfish,jboss,weblogic,mybatis,vaadin,zk,osgi,jersey,resteasy,camel,log4j2
